Update

diff --git a/arch-pihole b/arch-pihole
--- a/arch-pihole
+++ b/arch-pihole
@@ -1,36 +1,44 @@
-#!/bin/bash
+##!/bin/bash
 # -*- coding: utf-8 -*-
 
 # ENTER PASSWORDS =========================================================================================
 while true; do
-echo -n "Enter new root password [minimum 8 characters]: "; read -rs ROOT_PASS
+echo -en "\n\e[1;36mEnter new root password [\e[1;33mMin. 8 chars\e[1;36m]: "; read -rs ROOT_PASS
+echo -en "\n\e[1;37mRepeat root password [\e[1;33mMin. 8 chars\e[1;37m]: "; read -rs ROOT_PASS_REPEAT
 
-[[ ! ${#ROOT_PASS} -ge 8 ]] && echo -e "\nPassword for \"root\" does not meet requirements" || break
+[[ "${ROOT_PASS}" != "${ROOT_PASS_REPEAT}" ]] && echo -e "\n\e[1;31mPasswords do not match" && continue
+
+[[ ! ${#ROOT_PASS} -ge 8 ]] && echo -e "\n\e[1;31mPassword for \e[1;33m\"root\"\e[1;31m does not meet requirements" || break
 done
-echo -e "\nPassword accepted"
+echo -e "\n\e[1;32mPassword accepted"
 
 while true; do
-echo -n "Enter Pi-Hole new root password [minimum 8 characters]: "; read -rs PIHOLE_PASS
+echo -en "\n\e[1;36mEnter Pi-Hole new root password [\e[1;33mMin. 8 chars\e[1;36m]: "; read -rs PIHOLE_PASS
+echo -en "\n\e[1;37mRepeat Pi-Hole root password [\e[1;33mMin. 8 chars\e[1;37m]: "; read -rs PIHOLE_PASS_REPEAT
 
-[[ ! ${#PIHOLE_PASS} -ge 8 ]] && echo -e "\nPassword for Pi-Hole user \"root\" does not meet requirements" || break
+[[ "${PIHOLE_PASS}" != "${PIHOLE_PASS_REPEAT}" ]] && echo -e "\n\e[1;31mPasswords do not match" && continue
+
+[[ ! ${#PIHOLE_PASS} -ge 8 ]] && echo -e "\n\e[1;31mPassword for Pi-Hole user \e[1;33m\"root\"\e[1;31m does not meet requirements" || break
 done
-echo -e "\nPassword accepted"
+echo -e "\n\e[1;32mPassword accepted"
 
 # PREPARE DISK ============================================================================================
 DISKS="$(lsblk -ln | grep disk | cut -d' ' -f1)"
-echo -e "Disks:\n${DISKS}\n"
+echo -e "\n\e[1;34mDisks:\n\e[1;33m${DISKS}"
 
 while true; do
-echo -n "Enter disk name for installation [example sda or nvme0n1]: "; read -r DISK_R
+echo -en "\n\e[1;36mEnter disk name for installation [\e[1;33msda, nvme0n1, mmcblk0, ...\e[1;36m]:\e[1;33m "; read -r DISK_R
 DISK=$(echo "${DISK_R}" | tr '[:upper:]' '[:lower:]')
-[[ ! -n "$(echo "${DISKS}" | grep -ow "${DISK}")" ]] && echo "Disk name not found" || break
+[[ ! -n "$(echo "${DISKS}" | grep -ow "${DISK}")" ]] && echo -e "\e[1;31mDisk name not found" || break
 done
 
 while true; do
-echo -n "All data on disk \"${DISK}\" will be destroyed. Continue? [yes/no]: "; read -r DESTROY
+echo -en "\n\e[1;31mAll data on disk \e[1;33m\"${DISK}\"\e[1;31m will be destroyed. \e[1;35mContinue? [\e[1;32myes\e[1;37m/\e[1;31mno\e[1;35m]:\e[1;33m "; read -r DESTROY
 [[ "${DESTROY}" =~ ^([yY][eE][sS])$ ]] && break
 [[ "${DESTROY}" =~ ^([nN][oO])$ ]] && exit 0
 done
+
+echo -e "\e[0m"
 
 echo -e "g\nw\n" | fdisk /dev/"${DISK}"
 echo -e 'mkpart "EFI system partition" fat32 1MiB 501MiB\nset 1 esp on\nmkpart "SYSTEM" ext4 501MiB 100%\nq\n' | parted "/dev/${DISK}"
@@ -39,6 +47,7 @@ PARTS=()
 while IFS='' read -r line; do PARTS+=("$line"); done < <(lsblk -ln /dev/"${DISK}" | grep part | cut -d' ' -f1)
 echo "${DISK}"
 echo "${PARTS[@]}" | tr ' ' '\n'
+
 
 # FORMAT ==================================================================================================
 mkfs.vfat /dev/"${PARTS[0]}"         # EFI   (/dev/nvme0n1p1)
